MoviesWebApplication/Controllers/ArtistsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesWebApplication;

namespace MoviesWebApplication.Controllers
{
    public class ArtistsController : Controller
    {
        private readonly MovieDBContext _context;

        public ArtistsController(MovieDBContext context)
        {
            _context = context;
        }

        // GET: Artists
        public async Task<IActionResult> ArtistList()
        {
            return View(await _context.Artists.ToListAsync());
        }

        // GET: Artists/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists
                .FirstOrDefaultAsync(m => m.Id == id);
            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // GET: Artists/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Artists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,NumberOfOscars")] Artist artist)
        {
            if (ModelState.IsValid)
            {
                _context.Add(artist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ArtistList));
            }
            return View(artist);
        }

        // GET: Artists/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists.FindAsync(id);
            if (artist == null)
            {
                return NotFound();
            }
            return View(artist);
        }

        // POST: Artists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,NumberOfOscars")] Artist artist)
        {
            if (id != artist.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(artist);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArtistExists(artist.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ArtistList));
            }
            return View(artist);
        }

        // GET: Artists/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists
                .FirstOrDefaultAsync(m => m.Id == id);
            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // POST: Artists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var artist = await _context.Artists.FindAsync(id);
            _context.Artists.Remove(artist);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(ArtistList));
        }

        private bool ArtistExists(int id)
        {
            return _context.Artists.Any(e => e.Id == id);
        }
    }
}

MoviesWebApplication/Controllers/ArtistsJobsInMoviesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesWebApplication;

namespace MoviesWebApplication.Controllers
{
    public class ArtistsJobsInMoviesController : Controller
    {
        private readonly MovieDBContext _context;
         
        public ArtistsJobsInMoviesController(MovieDBContext context)
        {
            _context = context;
        }

        // GET: ArtistsJobsInMovies
        public async Task<IActionResult> ArtistMoviesList(int artistId)
        {
            var currentArtist = _context.Artists.FirstOrDefault(a => a.Id == artistId);
            ViewBag.CurrentArtistName = currentArtist.Name;
            ViewBag.CurrentArtist=currentArtist;

            var movieDBContext = await _context.ArtistsJobsInMovies
                .Where(am => am.ArtistId == artistId)
                .Include(am => am.Movie).ToListAsync();

            return View(movieDBContext);
        }

        // GET: ArtistsJobsInMovies/Create

        [Authorize(Roles = "admin")]
        public IActionResult Create(int currentArtistId)
        {
            var currentArtist = _context.Artists.FirstOrDefault(a => a.Id == currentArtistId);
            var currentArtistJobsInMoviesIds = _context.ArtistsJobsInMovies.Where(am => am.ArtistId == currentArtistId).Select(am => am.MovieId);
            ViewBag.CurrentArtist = currentArtist;
            ViewBag.CurrentArtistName = currentArtist.Name;
            ViewBag.MoviesList = new SelectList(_context.Movies.Where(m => !currentArtistJobsInMoviesIds.Contains(m.Id)), "Id", "Name");
            return View();
        }

        // POST: ArtistsJobsInMovies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateRes([Bind("Id,MovieId,ArtistId,Job")] ArtistsJobsInMovie artistsJobsInMovie)
        {
            Artist artist = _context.Artists.FirstOrDefault(x => x.Id == artistsJobsInMovie.ArtistId);
            if (ModelState.IsValid)
            {
                Movie movie = _context.Movies.FirstOrDefault(x => x.Id == artistsJobsInMovie.MovieId);
                artistsJobsInMovie.Movie = movie;
                artistsJobsInMovie.Artist = artist;
                _context.Add(artistsJobsInMovie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(ArtistMoviesList), new { artistId = artist.Id });
            }
            var currentArtistJobsInMoviesIds = _context.ArtistsJobsInMovies.Where(am => am.ArtistId == artist.Id).Select(am => am.MovieId);
            ViewBag.ArtistId = artist.Id;
            ViewBag.ArtistName = artist.Name;
            ViewBag.MoviesList = new SelectList(_context.Movies.Where(m => !currentArtistJobsInMoviesIds.Contains(m.Id)), "Id", "Name");
            return View(artistsJobsInMovie);
        }


        // GET: ArtistsJobsInMovies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artistsJobsInMovie = await _context.ArtistsJobsInMovies
                .Include(a => a.Artist)
                .Include(a => a.Movie)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (artistsJobsInMovie == null)
            {
                return NotFound();
            }

            ViewBag.CurrentArtist = artistsJobsInMovie.Artist;

            return View(artistsJobsInMovie);
        }

        // POST: ArtistsJobsInMovies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var artistsJobsInMovie = await _context.ArtistsJobsInMovies.FindAsync(id);
            _context.ArtistsJobsInMovies.Remove(artistsJobsInMovie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(ArtistMoviesList), new { artistId = artistsJobsInMovie.ArtistId });
        }

        private bool ArtistsJobsInMovieExists(int id)
        {
            return _context.ArtistsJobsInMovies.Any(e => e.Id == id);
        }
    }
}

MoviesWebApplication/Controllers/MoviesController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ClosedXML.Excel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoviesWebApplication;

namespace MoviesWebApplication.Controllers
{
    public class MoviesController : Controller
    {
        private readonly MovieDBContext _context;

        public MoviesController(MovieDBContext context)
        {
            _context = context;
        }

        // GET: Movies
        public async Task<IActionResult> List()
        {
            var movieDBContext = _context.Movies.Include(m => m.Production);
            return View(await movieDBContext.ToListAsync());
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .Include(m => m.Production)
                .Include(m => m.ArtistsJobsInMovies)
                .ThenInclude(am => am.Artist)
                .Include(m => m.MoviesGenres)
                .ThenInclude(mg => mg.Genre)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }
            ViewBag.Picture = _context.Movies.Where(m => m.Id == id).Select(m => m.Picture);

            return View(movie);
        }

        // GET: Movies/Create
        [Authorize(Roles = "admin")]
        public IActionResult Create()
        {
            ViewData["ProductionName"] = new SelectList(_context.Productions, "Id", "Name");
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Duration,Picture,ProductionId,Soundtracks")] Movie movie)
        {
            Production pr = _context.Productions.FirstOrDefault(p => p.Id == movie.ProductionId);
            movie.Production = pr;


            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(List));
            }

            ViewData["ProductionName"] = new SelectList(_context.Productions, "Id", "Name", movie.ProductionId);
            return View(movie);
        }

        // GET: Movies/Edit/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            ViewData["ProductionName"] = new SelectList(_context.Productions, "Id", "Name", movie.ProductionId);
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Duration,Picture,ProductionId,Soundtracks")] Movie movie)
        {
            if (id != movie.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(List));
            }
            ViewData["ProductionId"] = new SelectList(_context.Productions, "Id", "Id", movie.ProductionId);
            return View(movie);
        }

        // GET: Movies/Delete/5
        [Authorize(Roles = "admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .Include(m => m.Production)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movies.FindAsync(id);
            _context.Movies.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(List));
        }

        private bool MovieExists(int id)
        {
            return _context.Movies.Any(e => e.Id == id);
        }


    }


}

MoviesWebApplication/Views/ArtistsJobsInMovies/ArtistMoviesList.cshtml
@model IEnumerable<MoviesWebApplication.ArtistsJobsInMovie>

<h1>Роботи артиста: @ViewBag.CurrentArtistName</h1>

@{
    if (User.IsInRole("admin"))
    {
        <form method="post" asp-controller="ArtistsJobsInMovies" asp-action="Create" asp-route-currentArtistId="@ViewBag.CurrentArtist.Id">
            <input type="submit" value="Додати роботу артиста" />
        </form>
    }
}

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Movie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Job)
            </th> 
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
        <tr>
            <td>
                @Html.ActionLink(item.Movie.Name, "Details", "Movies", routeValues: new {id = @item.Movie.Id})
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Job)
            </td>
            <td>
                    @{
                        if (User.IsInRole("admin"))
                        {
                            <a asp-action="Delete" asp-route-id="@item.Id">Видалити</a>
                        }
                    }
             </td>
        </tr>
        }
    </tbody>
</table>

<div>
   @Html.ActionLink("Повернутися назад", "ArtistList" ,"Artists" )
 </div>

MoviesWebApplication/Views/ArtistsJobsInMovies/Create.cshtml
@model MoviesWebApplication.ArtistsJobsInMovie

<h1>Нова робота артиста</h1>

<h4>Заповніть інформацію про нову роботу артиста</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateRes">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ArtistId" class="control-label"></label>
                <label>@ViewBag.CurrentArtistName</label>
                <input type="hidden" asp-for="ArtistId" value="@ViewBag.CurrentArtist.Id" />
            </div>
            <div class="form-group">
                <label asp-for="MovieId" class="control-label"></label>
                <select asp-for="MovieId" class="form-control" asp-items="@ViewBag.MoviesList as SelectList"></select>
            </div>
            <div class="form-group">
                <label asp-for="Job" class="control-label"></label>
                <input asp-for="Job" class="form-control" />
                <span asp-validation-for="Job" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Створити" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="ArtistMoviesList" asp-route-genreId="@ViewBag.CurrentArtist.Id">Повернутися назад</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MoviesWebApplication/Views/ArtistsJobsInMovies/Delete.cshtml
@model MoviesWebApplication.ArtistsJobsInMovie

<h1>Видалення</h1>

<h3>Ви впевнені, що хочете видалити фільм "@Model.Movie?.Name" як роботу артиста  "@Model.Artist?.Name"</h3>
<div> 
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Job)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Job)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Видалити" class="btn btn-danger" /> |
        <a asp-action="ArtistMoviesList" asp-route-genreId="@ViewBag.CurrentArtist.Id">Повернутися назад</a>
    </form>
</div>

MoviesWebApplication/Views/ArtistsJobsInMovies/Details.cshtml
@model MoviesWebApplication.ArtistsJobsInMovie

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ArtistsJobsInMovie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Job)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Job)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Movie)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Movie.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MoviesWebApplication/Views/ArtistsJobsInMovies/Edit.cshtml
@model MoviesWebApplication.ArtistsJobsInMovie

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ArtistsJobsInMovie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="MovieId" class="control-label"></label>
                <select asp-for="MovieId" class="form-control" asp-items="ViewBag.MovieId"></select>
                <span asp-validation-for="MovieId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ArtistId" class="control-label"></label>
                <select asp-for="ArtistId" class="form-control" asp-items="ViewBag.ArtistId"></select>
                <span asp-validation-for="ArtistId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Job" class="control-label"></label>
                <input asp-for="Job" class="form-control" />
                <span asp-validation-for="Job" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}